import React from 'react';
export const metadata = {
  title: "Analytics | My NextJs App",
  description: "Generated by create next app",
};

function Analytics() {
  // throw new Error('this is analytics intentional error');
  return (
    <div>
      This is Analytics Page
    </div>
  );
}

export default Analytics;