import CommonComponent from "@/app/Components/CommonComponent";

export const metadata = {
  title: "DashBoard | My NextJs App",
  description: "Generated by create next app",
};


export default function DashLayout({ children }) {
  // throw new Error('Intentional error in dashboard layout.');
  return (
    <html>
      <body>

      
      <div className="p-4 m-4">
        <div>
          <CommonComponent></CommonComponent>
        </div>
      This is Settings Layout
      <hr></hr>
      </div>
        {children}
        </body>
        </html>
  );
}
