import React from 'react';
export const metadata = {
  title: "Settings | My NextJs App",
  description: "Generated by create next app",
};

function Settings() {
  // throw new Error('Intentional Error in Settings Page');
  return (
    <div>
      This is Settings Page!
    </div>
  );
}

export default Settings;