import CommonComponent from "../Components/CommonComponent"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CommonComponent></CommonComponent>
        
        
        {children}</body>
    </html>
  )
}
