export const metadata = {
  title: "DashBoard | My NextJs App",
  description: "Generated by create next app",
};


export default function DashLayout({ children }) {
  // throw new Error('Intentional error in dashboard layout.');
  return (
    <html>
      <body>



      <div className="p-4 m-4">
      This is Dashboard Layout
      <hr></hr>
      </div>
        {children}
    </body>
    </html>
  );
}

