import React from 'react';
export const metadata = {
  title: "Analytics | My NextJs App",
  description: "Generated by create next app",
};

function Dashboard() {
  // throw new Error('this is Dashboard intentional error');
  return (
    <div>
      This is Dashboard Page
    </div>
  );
}

export default Dashboard;